### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by godreborn** [john-tornblom/ps5-payload-sdk#1]
I get this error: godreborn@GODREBORN-LAPTOP:~/ps5-payload-sdk$ make
cc -c -ffreestanding -fno-builtin -nostdlib -static -masm=intel -o crt1.o crt1.c
make: *** No rule to make target 'libkernel.sprx', needed by 'libkernel.c'.  Stop.

**Comment by john-tornblom** [comment]
Please read the [Prerequisites](https://github.com/john-tornblom/ps5-payload-sdk#prerequisites).
